$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1548194919353.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9d6d0b97784449659435f78c075751dd",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"abf8808b1a8c4e379267103d569d80d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":90},
            "size":{
              "width":500,
              "height":320}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d27805cbeae740619b0bf02715bafe5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":90},
                "size":{
                  "width":500,
                  "height":320}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"3e74c732ec86476fbcf0b4a1570e1e3b",
          "label":"idTextField",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":410,
              "y":220},
            "size":{
              "width":450,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"Digite seu RA"},
{
          "id":"7a2eba3241154eb9abca8cebbb87d39f",
          "label":"passwordTextField",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":410,
              "y":255},
            "size":{
              "width":450,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"Digite sua senha"},
{
          "id":"22ae90c099d24b86adaf3ed0230e8850",
          "label":"submit",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":410,
              "y":348},
            "size":{
              "width":450,
              "height":45}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        //"url":"page_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f07b3dc19e1f49b5b30955d5bdb554f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":410,
              "y":168},
            "size":{
              "width":200,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c1e6b48169249d6ace53271a7d6e9ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":410,
                  "y":168},
                "size":{
                  "width":200,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc6ec7a9b38e4d9084ae47c5f91472c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":750,
              "y":300},
            "size":{
              "width":100,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0465499b69847eab259c68f077f985b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":750,
                  "y":300},
                "size":{
                  "width":100,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Cadastro in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"cadastro.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"538bb8cea7964e3eb5fe9398a5bea9f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7FFD4},
            "location":{
              "x":390,
              "y":90},
            "size":{
              "width":250,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a31eab50d8c34595a6ba9d931f6acf5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7FFD4},
                "location":{
                  "x":390,
                  "y":90},
                "size":{
                  "width":250,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u9.png"}},
{
          "id":"241ab7c3ddfe4c8eb9de90fb39d968a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xE556C04E},
            "location":{
              "x":640,
              "y":90},
            "size":{
              "width":250,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0988f850e6748d0ba189558468d0160",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xE556C04E},
                "location":{
                  "x":640,
                  "y":90},
                "size":{
                  "width":250,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u11.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "abf8808b1a8c4e379267103d569d80d6":{
      "scriptId":"u0"},
    "d27805cbeae740619b0bf02715bafe5e":{
      "scriptId":"u1"},
    "3e74c732ec86476fbcf0b4a1570e1e3b":{
      "scriptId":"u2"},
    "7a2eba3241154eb9abca8cebbb87d39f":{
      "scriptId":"u3"},
    "22ae90c099d24b86adaf3ed0230e8850":{
      "scriptId":"u4"},
    "f07b3dc19e1f49b5b30955d5bdb554f5":{
      "scriptId":"u5"},
    "2c1e6b48169249d6ace53271a7d6e9ca":{
      "scriptId":"u6"},
    "dc6ec7a9b38e4d9084ae47c5f91472c9":{
      "scriptId":"u7"},
    "d0465499b69847eab259c68f077f985b":{
      "scriptId":"u8"},
    "538bb8cea7964e3eb5fe9398a5bea9f6":{
      "scriptId":"u9"},
    "a31eab50d8c34595a6ba9d931f6acf5b":{
      "scriptId":"u10"},
    "241ab7c3ddfe4c8eb9de90fb39d968a7":{
      "scriptId":"u11"},
    "b0988f850e6748d0ba189558468d0160":{
      "scriptId":"u12"}}});