$axure.loadCurrentPage({
  "url":"page_2.html",
  "generationDate":new Date(1548194919575.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0663c9b9aba24d9d92247f4948ada796",
    "type":"Axure:Page",
    "name":"Page 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3fe18a52f8dd477789ff0417ce912539",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":210,
              "height":651}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94abb522a32f4798950a555acea6b44a",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":210,
                  "height":651}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1682601f075a4be798a0165e5a4bf54c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be8d34ff79614d0e8445c868f20a1963",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"2271e123a2e741a98f49034fb66cfcd2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f574e280e5844959a826121d58e051a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"fe0648ba655d46e48486fcbba179db26",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"51d118cf668048e19b60e7e47cfcb69c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":100},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"74aab94d00de45d7aa9ebd3efa2ae614",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e78246785694e2483cfd9c6da33c6ca",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":150},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"d8e04f22e5fa4a77ac7ee6e040d4c172",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":200},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e832e0b66b92447abaffb9a51f36e213",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":200},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"bd92628690c44832b632e1003597d12a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":250},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfcf0022e5ee4a32945f82f945b88384",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":250},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"7d4631821d7c4398893b5eba5310d01c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":300},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efc75f12d2574cbc99fdf8bde2384123",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":300},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"c8e490ba3f604730a65138a4db125d87",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":350},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"121a8a604ce04603846b50b9677050cd",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":350},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"3a215baba9db43d888204aa7dae199a1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":400},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f9af64cec664b6a8449b400e3fb793a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"5d7a6d6d5bc449469c64c4e387b9190d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":450},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1e8faca66a69480a9a8f3318182dc0c8",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":450},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"1ffae5626b1d474ea390ca9b8025b4dd",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":500},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a9e4d006e279452385d623f7c25d1722",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":500},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u2.png"}},
{
                  "id":"bebfa3da8f244065860e0505b2a50ea5",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":550},
                    "size":{
                      "width":210,
                      "height":51}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"649fe1678a9c4feb846b7aa7214a81aa",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":550},
                        "size":{
                          "width":210,
                          "height":51}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u24.png"}},
{
                  "id":"b2e031e316d74d8a97e3676753a9341f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":601},
                    "size":{
                      "width":210,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7cfa62add73642f881efcf14d3bced1a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":601},
                        "size":{
                          "width":210,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_2/u26.png"}}]}]},
{
          "id":"3109b8586d5142cba89f055ea22b4c5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "size":{
              "width":1350,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"959eef1c1fcc4c05812a420eac9fadf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "size":{
                  "width":1350,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_2/u28.png"}},
{
          "id":"eb7af43e57bc4676a4923587bb033732",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1110,
              "y":17},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78d7ae989e3143c9964203206687a071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1110,
                  "y":17},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3222773d94ad489f9c2efdf4b470da24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1230,
              "y":10},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60e1ed67cf794a489ecd82287bd57f39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1230,
                  "y":10},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_2/u32.png"}},
{
          "id":"36e0c6f1f02841dfa7afc0e1a52386c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":7},
            "size":{
              "width":80,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55a10e2e72164cf095f74b758e6d276d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":7},
                "size":{
                  "width":80,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_2/u34.png"}},
{
          "id":"7a2348ebfdd3423380dad7316b614f0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":50},
            "size":{
              "width":1140,
              "height":651}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"390b18a998ac4a198f0d3e7bda7ff437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":50},
                "size":{
                  "width":1140,
                  "height":651}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_2/u36.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3fe18a52f8dd477789ff0417ce912539":{
      "scriptId":"u0"},
    "94abb522a32f4798950a555acea6b44a":{
      "scriptId":"u1"},
    "1682601f075a4be798a0165e5a4bf54c":{
      "scriptId":"u2"},
    "be8d34ff79614d0e8445c868f20a1963":{
      "scriptId":"u3"},
    "2271e123a2e741a98f49034fb66cfcd2":{
      "scriptId":"u4"},
    "2f574e280e5844959a826121d58e051a":{
      "scriptId":"u5"},
    "fe0648ba655d46e48486fcbba179db26":{
      "scriptId":"u6"},
    "51d118cf668048e19b60e7e47cfcb69c":{
      "scriptId":"u7"},
    "74aab94d00de45d7aa9ebd3efa2ae614":{
      "scriptId":"u8"},
    "2e78246785694e2483cfd9c6da33c6ca":{
      "scriptId":"u9"},
    "d8e04f22e5fa4a77ac7ee6e040d4c172":{
      "scriptId":"u10"},
    "e832e0b66b92447abaffb9a51f36e213":{
      "scriptId":"u11"},
    "bd92628690c44832b632e1003597d12a":{
      "scriptId":"u12"},
    "bfcf0022e5ee4a32945f82f945b88384":{
      "scriptId":"u13"},
    "7d4631821d7c4398893b5eba5310d01c":{
      "scriptId":"u14"},
    "efc75f12d2574cbc99fdf8bde2384123":{
      "scriptId":"u15"},
    "c8e490ba3f604730a65138a4db125d87":{
      "scriptId":"u16"},
    "121a8a604ce04603846b50b9677050cd":{
      "scriptId":"u17"},
    "3a215baba9db43d888204aa7dae199a1":{
      "scriptId":"u18"},
    "1f9af64cec664b6a8449b400e3fb793a":{
      "scriptId":"u19"},
    "5d7a6d6d5bc449469c64c4e387b9190d":{
      "scriptId":"u20"},
    "1e8faca66a69480a9a8f3318182dc0c8":{
      "scriptId":"u21"},
    "1ffae5626b1d474ea390ca9b8025b4dd":{
      "scriptId":"u22"},
    "a9e4d006e279452385d623f7c25d1722":{
      "scriptId":"u23"},
    "bebfa3da8f244065860e0505b2a50ea5":{
      "scriptId":"u24"},
    "649fe1678a9c4feb846b7aa7214a81aa":{
      "scriptId":"u25"},
    "b2e031e316d74d8a97e3676753a9341f":{
      "scriptId":"u26"},
    "7cfa62add73642f881efcf14d3bced1a":{
      "scriptId":"u27"},
    "3109b8586d5142cba89f055ea22b4c5b":{
      "scriptId":"u28"},
    "959eef1c1fcc4c05812a420eac9fadf5":{
      "scriptId":"u29"},
    "eb7af43e57bc4676a4923587bb033732":{
      "scriptId":"u30"},
    "78d7ae989e3143c9964203206687a071":{
      "scriptId":"u31"},
    "3222773d94ad489f9c2efdf4b470da24":{
      "scriptId":"u32"},
    "60e1ed67cf794a489ecd82287bd57f39":{
      "scriptId":"u33"},
    "36e0c6f1f02841dfa7afc0e1a52386c8":{
      "scriptId":"u34"},
    "55a10e2e72164cf095f74b758e6d276d":{
      "scriptId":"u35"},
    "7a2348ebfdd3423380dad7316b614f0f":{
      "scriptId":"u36"},
    "390b18a998ac4a198f0d3e7bda7ff437":{
      "scriptId":"u37"}}});